#!/bin/bash

battery_percentage=$(acpi | awk '{print $4}' | cut -f 1 -d "%")
battery_icon=""

if (($battery_percentage == 100)); then
	battery_icon=
else
	if (($battery_percentage > 75)); then
		battery_icon= 
        elif (($battery_percentage > 50)); then
		battery_icon=
	elif (($battery_percentage > 25)); then
		battery_icon=
        else
		battery_icon=
        fi
fi

echo "${battery_icon} ${battery_percentage}%"
